[application]
title=Software Rasterizer

[video]
# 0 = primary monitor, 1 = second monitor, 2 = third monitor, etc.
display_index=0
width=960
height=540
min_width=640
min_height=360
max_width=1280
max_height=720
#max_width=1920
#max_height=180
#max_width=3840
#max_height=2160
fullscreen=false
resizable=true

[renderer]
# Native build only. Web always uses the browser VSync (requestAnimationFrame).
target_fps=0
vsync=true

[debug]
show_fps=true

[web]
canvas_id=canvas
