#ifndef PLATFORM_KEYBOARD_H
#define PLATFORM_KEYBOARD_H

typedef enum PlatformKey
{
    PLATFORM_KEY_UNKNOWN = 0,
    PLATFORM_KEY_ESCAPE,
    PLATFORM_KEY_ENTER,
    PLATFORM_KEY_BACKSPACE,
    PLATFORM_KEY_TAB,
    PLATFORM_KEY_SPACE,
    PLATFORM_KEY_UP,
    PLATFORM_KEY_DOWN,
    PLATFORM_KEY_LEFT,
    PLATFORM_KEY_RIGHT,

    PLATFORM_KEY_COUNT
} PlatformKey;

#endif // PLAFORM_KEYBOARD_H
